// Generated by layout/gen.py from layout/macropad.json and layout/pins.json.
// Do not edit: change the JSON, then `just mp-gen`.
#pragma once

#include <stdint.h>

#define MATRIX_ROWS 5
#define MATRIX_COLS 6
#define MATRIX_COL2ROW 1
#define KEY_COUNT 22
#define ENCODER_COUNT 3

static const uint8_t MATRIX_ROW_PINS[MATRIX_ROWS] = {4, 5, 6, 7, 15};
static const uint8_t MATRIX_COL_PINS[MATRIX_COLS] = {16, 17, 18, 8, 9, 10};

// Slot -> event index: 0..KEY_COUNT-1 are K1..Kn, KEY_COUNT+e is encoder e's push, -1 is empty.
static const int8_t MATRIX_SLOT[MATRIX_ROWS][MATRIX_COLS] = {
    {0, 1, 2, 3, 4, 5},
    {6, 7, 8, 9, 10, 11},
    {12, 13, 14, 15, 16, 17},
    {18, -1, 19, 20, -1, 21},
    {22, 23, 24, -1, -1, -1},
};

static const char *const KEY_IDS[KEY_COUNT] = {"K1", "K2", "K3", "K4", "K5", "K6", "K7", "K8", "K9", "K10", "K11", "K12", "K13", "K14", "K15", "K16", "K17", "K18", "K19", "K20", "K21", "K22"};
static const char *const ENCODER_IDS[ENCODER_COUNT] = {"E1", "E2", "E3"};
static const uint8_t ENCODER_PIN_A[ENCODER_COUNT] = {11, 13, 21};
static const uint8_t ENCODER_PIN_B[ENCODER_COUNT] = {12, 14, 47};

#define PIN_I2S_BCLK 38
#define PIN_I2S_WS 39
#define PIN_I2S_MIC_SD 40
#define PIN_I2S_AMP_DIN 41
#define PIN_AMP_SD 46

#define PIN_OLED_SCK 42
#define PIN_OLED_MOSI 2
#define PIN_OLED_CS 48
#define PIN_OLED_DC 43
#define PIN_OLED_RES -1  // -1: tied to EN

#define PIN_VBAT_ADC 1
#define PIN_CHARGE_STAT 44
#define PIN_MIC_LED 45
#define PIN_BOOT 0
